CREATE TABLE Owner (
Owner_Id TYPE INT,
CONSTRAINT PK_Owner PRIMARY KEY(Owner_Id)
);

CREATE TABLE Rental_Company(
C_OwnerID TYPE INT,
RC_Name TYPE VARCHAR(50),
CONSTRAINT PK_RComp PRIMARY KEY(C_OwnerID),
FOREIGN KEY(C_OwnerID) REFERENCES Owner(Owner_Id)
);

CREATE TABLE Bank(
B_OwnerID TYPE INT,
Bank_name TYPE VARCHAR(50),
CONSTRAINT PK_Bank PRIMARY KEY(B_OwnerID),
FOREIGN KEY(B_OwnerID) REFERENCES Owner(Owner_Id)
);

CREATE TABLE Individual(
I_OwnerID TYPE INT,
Fname TYPE VARCHAR(50),
Lname TYPE VARCHAR(50),
CONSTRAINT PK_Indi PRIMARY KEY(I_OwnerID),
FOREIGN KEY(I_OwnerID) REFERENCES Owner(Owner_Id)
);

CREATE TABLE CAR(
Vehicle_ID TYPE INT,
Owner_ID TYPE INT,
Avail_StartDate TYPE DATE,
Avail_EndDate TYPE DATE,
Model TYPE VARCHAR(50),
Year TYPE INT,
CONSTRAINT PK_Car PRIMARY KEY(Vehicle_ID),
Foreign Key(Owner_ID) references Owner(Owner_Id)
);

CREATE TABLE CAR_TYPE(
Type_ID TYPE INT,
Daily_Rate TYPE INT,
Weekly_Rate TYPE INT,
CONSTRAINT PK_Type PRIMARY KEY(Type_ID),
);

CREATE TABLE Van(
    Type_ID INT,
    FOREIGN KEY(Type_ID) REFERENCES Car_Type(Type_ID));


CREATE TABLE Compact( Type_ID INT, FOREIGN KEY(Type_ID) REFERENCES Car_Type(Type_ID));

CREATE TABLE Truck( Type_ID INT, FOREIGN KEY(Type_ID) REFERENCES Car_Type(Type_ID));

CREATE TABLE SUV( Type_ID INT, FOREIGN KEY(Type_ID) REFERENCES Car_Type(Type_ID));

CREATE TABLE Large( Type_ID INT, FOREIGN KEY(Type_ID) REFERENCES Car_Type(Type_ID));

CREATE TABLE Medium( Type_ID INT, FOREIGN KEY(Type_ID) REFERENCES Car_Type(Type_ID));

CREATE TABLE Luxury( Type_ID INT, FOREIGN KEY(Type_ID) REFERENCES Car_Type(Type_ID));

CREATE TABLE Regular( Type_ID INT, FOREIGN KEY(Type_ID) REFERENCES Car_Type(Type_ID));

CREATE TABLE RENTS(
Vehicle_Id TYPE INT,
Cust_ID TYPE INT,
Start_Date TYPE. DATE,
Return_Date TYPE DATE,
No_of_Weeks TYPE INT,
Daily_Rate TYPE INT,
Weekly_Rate TYPE INT,
No_of_days TYPE INT,
Scheduled TYPE INT,
Amount_Due TYPE INT,
CONSTRAINT PK_RENT PRIMARY KEY(Vehicle_ID,Cust_ID),
);

CREATE TABLE CUSTOMER(
Cust_ID TYPE INT,
Phone TYPE INT,
CONSTRAINT PK_Cust PRIMARY KEY(Cust_Id),
);

CREATE TABLE Individual_Cust(
Cust_ID TYPE INT,
Initial_Name TYEP VARCHAR(50),
LName TYPE VARCHAR(50),
CONSTRAINT PK_iND PRIMARY KEY(Cust_ID),
FOREIGN KEY(Cust_Id) REFERENCES Customer(Cust_ID)
);

CREATE TABLE Company(
Cust_ID TYPE INT,
CName TYPE VARCHAR(50)
CONSTRAINT PK_cOMP PRIMARY KEY(Cust_ID),
FOREIGN KEY(Cust_ID) REFERENCES Customer(Cust_ID)
);
